run:
	pbsmrtpipe  pipeline $$(pwd)/workflow_id.xml --debug  -e e_01:$$(pwd)/input.txt --preset-xml=$$(pwd)/preset.xml    --output-dir=$$(pwd)/job_output
falcon:
	pb-falcon ../../FALCON-examples/run/synth0/fc_run.cfg
